
import { GoogleGenAI } from "@google/genai";

// CONSTANTES DEFINIDAS AQUI PARA EVITAR ERRO DE MODULO
const MODEL_NAME = 'gemini-2.5-flash-image';
const RANDOM_PROMPTS = [
  "A cute bear and a bunny having a picnic on a checkered blanket with watermelon and sandwiches.",
  "A cozy kitchen scene with a puppy baking cookies, flour messy on the counter.",
  "A bedroom with a fluffy dog writing a letter at a desk, with a fishbowl and posters.",
  "Cute animals ordering burgers at a cafe stand with a striped awning.",
  "Jesus sitting in a garden surrounded by cute smiling children.",
  "A nativity scene with cute baby Jesus, Mary, Joseph, and farm animals.",
  "A bear fishing on a wooden dock with a little duckling watching.",
  "A festive Christmas scene with puppies decorating a gingerbread house.",
  "Cute cats building a sandcastle on the beach under the sun.",
  "A bunny watering plants in a greenhouse full of flowers and pots.",
  "Jesus holding a little lamb in his arms, surrounded by flowers.",
  "Two teddy bears hugging in a cozy living room with a fireplace.",
  "A little mouse and a bear reading a book under a big tree."
];

// ATENÇÃO: Usando import.meta.env.VITE_API_KEY para compatibilidade com Vite/Netlify
const API_KEY = import.meta.env.VITE_API_KEY;

if (!API_KEY) {
  console.warn("API Key não encontrada! Configure VITE_API_KEY no Netlify.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY || "CHAVE_FALTANDO" });

export const generateBobbieGoodsArt = async (base64Image: string): Promise<string> => {
  // Remove header if present (e.g., "data:image/jpeg;base64,")
  const base64Data = base64Image.split(',')[1] || base64Image;
  const mimeType = base64Image.match(/data:([a-zA-Z0-9]+\/[a-zA-Z0-9-.+]+).*,.*/)?.[1] || 'image/jpeg';

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: mimeType,
              data: base64Data,
            },
          },
          {
            text: "Transform this image into a cute Bobbie Goods style coloring page illustration. Keep the exact composition, characters, and objects, but draw them with thick, smooth outlines suitable for coloring. Make it super cute and cozy.",
          },
        ],
      },
    });

    return extractImageFromResponse(response);
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const generateRandomLineArt = async (): Promise<string> => {
  const randomPrompt = RANDOM_PROMPTS[Math.floor(Math.random() * RANDOM_PROMPTS.length)];
  
  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            text: `Create a black and white coloring page line art in the style of 'Bobbie Goods'. 
            Subject: ${randomPrompt}.
            Style details: Thick monoline outlines, very cute (kawaii) characters, minimal shading, pure white background, high contrast. 
            Make it look exactly like a page from a coloring book.`
          }
        ]
      }
    });

    return extractImageFromResponse(response);
  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
}

const extractImageFromResponse = (response: any): string => {
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const parts = candidates[0].content.parts;
      
      // Iterate to find the image part
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
           return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
      throw new Error("No image generated by the model.");
    }
    throw new Error("Empty response from Gemini.");
}
