import { GoogleGenAI } from "@google/genai";
import { MODEL_NAME, RANDOM_PROMPTS } from '../constants';

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generateBobbieGoodsArt = async (base64Image: string): Promise<string> => {
  // Remove header if present (e.g., "data:image/jpeg;base64,")
  const base64Data = base64Image.split(',')[1] || base64Image;
  const mimeType = base64Image.match(/data:([a-zA-Z0-9]+\/[a-zA-Z0-9-.+]+).*,.*/)?.[1] || 'image/jpeg';

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: mimeType,
              data: base64Data,
            },
          },
          {
            text: "Transform this image into a cute Bobbie Goods style coloring page illustration. Keep the exact composition, characters, and objects, but draw them with thick, smooth outlines suitable for coloring. Make it super cute and cozy.",
          },
        ],
      },
      config: {
        // System instruction removed from config as it is being passed via text prompt logic
      }
    });

    return extractImageFromResponse(response);
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const generateRandomLineArt = async (): Promise<string> => {
  const randomPrompt = RANDOM_PROMPTS[Math.floor(Math.random() * RANDOM_PROMPTS.length)];
  
  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            text: `Create a black and white coloring page line art in the style of 'Bobbie Goods'. 
            Subject: ${randomPrompt}.
            Style details: Thick monoline outlines, very cute (kawaii) characters, minimal shading, pure white background, high contrast. 
            Make it look exactly like a page from a coloring book.`
          }
        ]
      }
    });

    return extractImageFromResponse(response);
  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
}

const extractImageFromResponse = (response: any): string => {
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const parts = candidates[0].content.parts;
      
      // Iterate to find the image part
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
           return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
      throw new Error("No image generated by the model.");
    }
    throw new Error("Empty response from Gemini.");
}